# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Burning Daylight
email: alexander@burningdaylight.io
description: >- # this means to ignore newlines until "baseurl:"
  A space for some of my things.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  n0mn0m
favicon: /assets/icons/favicon.png
hide_share_buttons: true


# Build settings
#theme: bulma-clean-theme
# With GitHub Pages Gem
remote_theme: chrisrhymes/bulma-clean-theme
theme_color: #654870FF;
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from

livereload: true

paginate: 5
paginate_path: "/blog/page:num"

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      hide_hero: true
#  -
#    scope:
#      path: ""
#      type: "posts"

#collections:
#  posts:
#    output: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
